# Generated by Django 4.0.6 on 2022-07-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitehits',
            name='visitors',
            field=models.CharField(default='visitor', max_length=254),
        ),
    ]
